export const GalleryData=[
    {
        id:1,
        url:"https://source.unsplash.com/random/700*500/?computer+dark",
    },
    {
        id:2,
        url:"https://source.unsplash.com/random/700*500/?coder",
    },
    {
        id:3,
        url:"https://source.unsplash.com/random/700*500/?programer",
    },
    {
        id:4,
        url:"https://source.unsplash.com/random/700*500/?programer",
    },
    {
        id:5,
        url:"https://source.unsplash.com/random/700*500/?programer",
    },
    {
        id:6,
        url:"https://source.unsplash.com/random/700*500/?programer",
    },
    {
        id:7,
        url:"https://source.unsplash.com/random/700*500/?programer",
    },
    {
        id:8,
        url:"https://source.unsplash.com/random/700*500/?programer",
    },
    {
        id:9,
        url:"https://source.unsplash.com/random/700*500/?programer",
    },
]